#!/usr/bin/env node
/*eslint-disable*/
/**
 * This script parses emojione's sprites css and prints an ES6 module
 * that exports an object that maps each codepoint to its CSS position.
 *
 * Sample output:
 *
 * export default {
 * {'0023-20E3':'2.85714% 0%'},
 * {'0030-20E3':'71.42857% 51.42857%'},
 * {'0031-20E3':'0% 2.85714%'},
 * {'0032-20E3':'2.85714% 2.85714%'},
 * ...
 */
'use strict';

const fs = require('fs');
const path = require('path');

const COMMENT = `/*eslint-disable */
// Do not edit!
// This file was auto-generated by ${path.basename(__filename)}
`;

const FILENAME = '/../node_modules/emojione/assets/sprites/emojione.sprites.css';
const REGEXP = /\.emojione-([\w-]+)\s*{\s*background-position:\s*([\d.%\s]+);/g;

const css = fs.readFileSync(__dirname + FILENAME).toString().replace(/\n/g, '');

const positions = [];

let match;
while (match = REGEXP.exec(css)) positions.push([match[1], match[2]]);

const str = positions.map(p => `'${p[0]}':'${p[1]}'`).join(',\n');

console.log(`${COMMENT}export default {\n${str}};`);
